// templates/user_main_template.c
#include <stdio.h>
#include <math.h> // For fabs
#include "{{HEADER_NAME}}" 

// 简单的模拟函数...
{{DATA_TYPE}} simulate_system_response({{DATA_TYPE}} current_value, {{DATA_TYPE}} control_output, {{DATA_TYPE}} sample_time) {
    // ... (与之前相同)
}

int main() {
    printf("Multi-PID Controller Example using {{FUNCTION_PREFIX}} functions.\n");
    printf("Generated by YJ Studio Advanced PID Code Generator.\n");
    printf("Timestamp: {{TIMESTAMP}}\n\n");

    // --- PID 实例声明 ---
{{PID_INSTANCE_DECLARATIONS}}

    printf("--- Initializing PID Controllers ---\n");
    // --- PID 实例初始化 ---
{{PID_INSTANCE_INITIALIZATIONS}}

    printf("\n--- Example PID Run (demonstrating first instance or specific logic) ---\n");
    // --- 示例计算 (这部分需要仔细设计如何展示多个PID) ---
{{PID_EXAMPLE_COMPUTATIONS}}
    // 例如，您可以只演示第一个PID，或者如果您有特定的多PID交互逻辑，
    // 可以在Python中构建更复杂的 {{PID_EXAMPLE_COMPUTATIONS}} 块。
    // 简单的做法是，Python为每个PID实例生成一小段独立的演示代码。

    printf("\nExample run finished.\n");
    return 0;
}